version: '3.9'

services:
  #Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./my-money-app:/var/www
      - ./dockerFiles/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - my-money-laravel
      - db

  # Database Service
  db:
    image: mysql
    container_name: mysql-my-money
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my_money_db
      MYSQL_ROOT_PASSWORD: password

  # Application Service
  my-money-laravel:
    container_name: my-money-laravel
    build: 
      context: ./dockerFiles/php
      dockerfile: Dockerfile
    volumes:
      - ./my-money-app:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
